#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-qa =						\
	papers/qa/packages.tex					\
	papers/qa/main.tex					\
	papers/qa/references.bib				\
	papers/qa/01_einleitung.tex				\
	papers/qa/02_definition.tex				\
	papers/qa/03_drehung.tex				\
	papers/qa/04_eigenschaften.tex				\
	papers/qa/05_ableitung.tex

