#
# Makefile
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	jordan_kurve.pdf	\
	strategie_kreis.pdf		\
	strategie_konvexe_polygone.pdf	\
	strategie_einfache_polygone.pdf	\
	triangulierung.pdf

jordan_kurve.pdf:	jordan_kurve.tex
	pdflatex jordan_kurve.tex

strategie_kreis.pdf:	strategie_kreis.tex
	pdflatex strategie_kreis.tex

strategie_konvexe_polygone.pdf:	strategie_konvexe_polygone.tex
	pdflatex strategie_konvexe_polygone.tex

strategie_einfache_polygone.pdf:	strategie_einfache_polygone.tex
	pdflatex strategie_einfache_polygone.tex

triangulierung.pdf:	triangulierung.tex
	pdflatex triangulierung.tex