#
# Makefile.inc -- dependencies for this article
#
# (c) 2026 Gian Cavegn, OST Ostschweizer Fachhochschule
#
dependencies-bessel =						\
	papers/bessel/packages.tex				\
	papers/bessel/main.tex					\
	papers/bessel/references.bib			\
	papers/bessel/teil0.tex					\
	papers/bessel/teil1.tex					\
	papers/bessel/teil2.tex					\
	papers/bessel/teil3.tex					\
	papers/bessel/images/besselj.dat		\
	papers/bessel/images/besselj-zeros.dat	\

 

