#
# Makefile -- make file for the paper aircraft
# (c) 2020 Prof Dr Andreas Mueller
#
all:	eigenwerte.pdf komplexe-ebene.pdf

eigenwerte.pdf:	eigenwerte.tex
	pdflatex eigenwerte.tex

komplexe-ebene.pdf:	komplexe-ebene.tex
	pdflatex komplexe-ebene.tex